### ISSUE TITLE
樣式調整：調整所有頁面的UI

### ISSUE THREAD

**Issue by yinmin8610** [MonospaceTW/monosparta-diving-app#100]
- HEADER
- [x] 點了會有藍色區塊

- 首頁
- [x] 去掉卡片的橫軸滾輪
- [x] 卡片標題字大小都改16
- [x] 去掉卡片外框
- [x] 搜尋bar改成全寬
- [x] footer的email字改成“聯絡我們”

- 關鍵字搜尋頁面
- [x] 關鍵字搜尋完加上結果筆數
- [x] 加上Statusbar height

- 知識首頁
- [x] header拿掉

- 知識詳細頁面
- [x] 文章分類的標籤按鈕改成一般標籤

- 潛店詳細頁面
- [x] 輪播圖：輪播的點點位置移到下面一點、小一點
- [x] 營業時間：行距調大
- [x] 內容的字的行距太窄、大小
- [x] 每則評論加上時間
- [x] 評論星星預設給4顆🌟

- [x] 初始畫面
- [x] icon

**Comment by yinmin8610** [comment]
搜尋頁面
輪播圖：點點下面一點、小一點
營業時間：滑動、行距
字的行距太窄、大小

HEADER
點了會有藍色區塊

首頁：去掉橫滾輪、標題自行都改15、卡片外框

**Comment by yinmin8610** [comment]
@jasminesie @hikarunost 請幫忙測試，
測試方法：掃QRCODE，根據每個頁面的調整和[設計稿](https://xd.adobe.com/spec/ab01aae0-b996-4438-5567-686b10a2407c-dd30/)比對

**Comment by hikarunost** [comment]
@ssiyang @yinmin8610 我測試完了，以下是我的回饋，可以參考
*   測試的手機型號：iphone6s
*   回饋
    *   關鍵字搜尋要再加上分頁，一頁15筆(後端)
    *   關鍵字搜尋結果的筆數若超過99會顯示99+
    *   首頁的搜尋框上方的空白感覺可以再少一點，搜尋結果頁面也是
    *   潛點/潛店的詳細頁面的地圖的地址改到「所在位置」的下方，不是同一行
　*   文章詳細頁面的部分，上方是不是可以不要放「探索知識」，改成放文章標題呢？
　　 還有，作者的部分可以不要寫成by，直接寫中文的「作者」兩個字呢？
　　 還有，日期的部分是不是可以不用寫「日期」兩個字，直接寫日期就好呢？

**Comment by yinmin8610** [comment]
已把需要改的項目寫成新issue
