### ISSUE TITLE
改善UI2.0

### ISSUE THREAD

**Issue by jasminesie** [MonospaceTW/monosparta-diving-app#107]
- [ ] 修改首頁介紹文字顏色
- [x] 修改電話格式
- [x] 修改篩選功能Prototype細節
- [x]  潛點潛店初始和篩選完列表要加總共筆數
- [x]  補齊錯誤頁面的字(等前後端確定)
- [x]  標準字設計
- [x]  LOGO襯底色
- [x]  Loading畫面Gif
- [x]  定義服務網站名稱
- [x]  首頁搜尋bar改成全寬
- [x]  關鍵字搜尋完加上結果筆數
- [x]  評論加上時間
- [x]  email改成聯絡我們
- [x]  知識header拿掉
- [x]  篩選結果 文章 補空狀態
- [x]  空白欄位寫“尚無資料”
- [x]  先不要【文章分類標籤】

**Comment by jasminesie** [comment]
@yinmin8610  @ssiyang 請幫我測試目前的UI有沒有甚麼地方還需要修改的

**Comment by yinmin8610** [comment]
為提供logo及Loading畫面Gif的連結，其他ok
