### ISSUE TITLE
篩選結果是“無”的頁面

### ISSUE THREAD

**Issue by yinmin8610** [MonospaceTW/monosparta-diving-app#129]
- [x] - 潛點篩選結果
- [x] - 潛店篩選結果
- [x] - 文章列表結果

**Comment by ssiyang** [comment]
@lukechu1997 @hikarunost @jasminesie 請幫忙測試
測試內容: 當潛點/潛店篩選結果以及文章列表個數為0時，會出現"沒有結果"的畫面
測試方法: 潛點: 北部/高階
                潛店:  北部/證照課程
                文章: 旅遊分類
