### ISSUE TITLE
ios上架

### ISSUE THREAD

**Issue by yinmin8610** [MonospaceTW/monosparta-diving-app#152]
8/31 截圖問題被拒絕，已重新提交申請

**Comment by anntsai2356** [comment]
IOS已上架
mentor的建議：
APP 的資訊需要再更新一下，主要有兩個部分，
1. app 標題的副標應該要有 潛水 關鍵字 - 因為 潛店/潛點 應該不會是使用者搜尋 app 的第一關鍵字，會導致 app 曝光率不夠高
2. app screenshots 應該要再編排過 - 如果直接使用截圖雖然符合需求，但並不夠吸引人
