### ISSUE TITLE
USER STORY：第二版

### ISSUE THREAD

**Issue by smallkawa** [MonospaceTW/monosparta-diving-app#163]
更新USER STORY，重新討論需要新增的項目。
文件可以在[Notion](https://www.notion.so/monosparta1/user-story-d23c721bef84451994708dd857422df2)檢視並更新。

**Comment by anntsai2356** [comment]
@smallkawa @bryanpalau 
今天大家列出所有 user story，可以在 Notion 的[ User Story ](https://www.notion.so/monosparta1/User-Story-d23c721bef84451994708dd857422df2)檢視。

並整理列出的 user story，可以在 Notion 的[ Reorganize User Story ](https://www.notion.so/monosparta1/Reorganize-User-Story-336523b746c9466d96163ced8996872c)檢視，今天檢視完篩選、交流、媒合，還剩下資訊和其他。

**Comment by smallkawa** [comment]
今天上午已將User story 分類，下午進行篩選決定目標。

時間：上午十一點到十二點

**Comment by smallkawa** [comment]
今天下午將User story 收斂完成決定了要做的部分。
檔案可至[雲端](https://docs.google.com/document/d/1t1kXvkgLkA6dTsAMv9js-bIgsjkWWpa_KUGYorjUkH0/edit?usp=sharing)查看。

時間：下午一點半到三點半
