### ISSUE TITLE
persona: 第二版

### ISSUE THREAD

**Issue by bryanpalau** [MonospaceTW/monosparta-diving-app#165]
藉由定義出人物誌，更精確瞭解使用者的使用需求，鎖定潛水客群，界定現階段所需功能       

 - [ ] 連結待補

**Comment by smallkawa** [comment]
經過和設計mentor討論後，因為目前APP尚在成型階段，潛水APP受眾較小，此版做persona需求沒有那麼必要，因此關閉本項目。
