### ISSUE TITLE
首頁加入ActivityIndicator功能

### ISSUE THREAD

**Issue by ssiyang** [MonospaceTW/monosparta-diving-app#73]
使用者在打開App時，在首頁部分加入loading圖示，提醒使用者目前首頁正在讀取資料中。

**Comment by ssiyang** [comment]
目前loading圖示使用react native提供的原生圖示，等設計稿完成後將會更新成新的loading圖示

**Comment by ssiyang** [comment]
@jasminesie  請幫忙測試
測試方法: APP開啟至首頁顯示資料期間，有Gif圖示產生，請幫忙看看是否符合設計稿

**Comment by jasminesie** [comment]
可以!!
