### ISSUE TITLE
新增error page

### ISSUE THREAD

**Issue by yinmin8610** [MonospaceTW/monosparta-diving-app#78]
後端回傳錯誤時連結到error page

**Comment by ssiyang** [comment]
@lukechu1997 @hikarunost @jasminesie 請幫忙測試
測試內容: 
1. 首頁超過10秒無法從資料庫抓到資料時，會跳轉到error page
2. 有連結API的功能，只要從伺服器回傳500都會跳轉到error page
測試方法:
修改api網址位置、關閉資料庫
