### ISSUE TITLE
API介接：在潛點潛店的詳細頁面串新增評論API

### ISSUE THREAD

**Issue by yinmin8610** [MonospaceTW/monosparta-diving-app#98]
在潛點潛店詳細頁面的評論，讓使用者可以新增評論，並且能在下方看到自己的評論內容，不限制留言次數，新增的評論會在最上方

**Comment by yinmin8610** [comment]
在潛點潛店詳細頁面的評論，讓使用者可以新增評論，並且能在下方看到自己的評論內容

**Comment by yinmin8610** [comment]
@lukechu1997 @hikarunost 請幫忙測試
測試方法：在詳細潛點及詳細潛店頁面最下方的評論，新增任何訊息以及點擊星數，按下“寫好了”按鈕，確定自己留言能在下方看見，若是在新增訊息時，要清空內容，可以點擊“先不要”按鈕來清空訊息。

**Comment by yinmin8610** [comment]
目前新增的評論會在最下方，希望能改成在最上方@lukechu1997 @hikarunost

**Comment by hikarunost** [comment]
> @lukechu1997 @hikarunost 請幫忙測試
> 測試方法：在詳細潛點及詳細潛店頁面最下方的評論，新增任何訊息以及點擊星數，按下“寫好了”按鈕，確定自己留言能在下方看見，若是在新增訊息時，要清空內容，可以點擊“先不要”按鈕來清空訊息。

潛點和潛店都測試完成，可以點擊星星、刪除編輯中的評論、新增評論。
有兩個可以改善的點：
1. 星星在點擊時不太順暢，建議可以把星星的間距拉寬，比較好點擊。
2. 評論送出時要五秒才會送出評論，有點延遲，建議可以改善反應時間。

**Comment by yinmin8610** [comment]
@hikarunost 間距已調寬，目前評論送出後的反應時間大約是1秒，再請測試一次。

**Comment by hikarunost** [comment]
@yinmin8610 間距比較好看了，我這邊測評論送出的反應時間是2秒左右，可能不同手機的反應時間不一樣。
另外，建議寫評論處的星星可以置中擺放。

**Comment by yinmin8610** [comment]
和設計討論過後，不改變星星位置
