### ISSUE TITLE
頁面：導覽畫面

### ISSUE THREAD

**Issue by yinmin8610** [MonospaceTW/monosparta-diving-app#99]
使用者在第一次開啟APP時才會出現，在初始畫面結束後，有三頁的整面輪播圖，內容用來介紹這個APP的主要功能，滑完輪播可按確定按鈕關閉輪播，並且回到首頁

**Comment by yinmin8610** [comment]
@anntsai2356 請幫忙測試唷～
在第一次開啟app時才會有四頁的導覽畫面，若不是第一次開可以先卸載App再重新安裝

**Comment by anntsai2356** [comment]
@yinmin8610 已重新安裝測試，確認有四頁導覽頁面沒問題。
